### ISSUE TITLE
Avisos en ABM de Localidad y Tipo de Contacto

### ISSUE THREAD

**Issue by pabloabregu** [vladimirogaston/TP_Inicial_agenda#24]
Modificar los avisos al Agregar, Editar y Borrar una Localidad o Tipo de Contacto que ya existe.

**Comment by vladimirogaston** [comment]
Pablo no me queda claro que es lo que tengo que testear en esta issue.

**Comment by pabloabregu** [comment]
Hay que testear los avisos que se dan cuando se quiere agregar o editar una Localidad o Tipo de Contacto que ya existe  y borrar una Localidad o Tipo de Contacto en uso.
